

<?php


require "adminForm.phtml";


if(isset($_POST["submit"]))
{
    if(isset($_FILES["fileToUpload"]))
    {
        $uploader = new FileUploader();
        
        $media = $uploader->upload($_FILES["fileToUpload"]);
        
        echo "<pre>";
        print_r($media);
        echo "</pre>";
    }
}

?>

<!doctype html>
<html>
    <head>
        
    </head>
    <body>
        <a class="user_admin" href="index.php?route=adminUser">Gestion des utilisateurs</a>
        
        <a class="update_admin" href="index.php?route=adminUpdate">Editer un build</a>
        
        <form class="admin-form" action="" method="post" enctype="multipart/form-data">
            <fieldset>
                <h3>Créer un personnage</h3>
                <label for="charname">Nom du personnage</label>
                <input maxlength="255" type="text" name="charname" id="charname">
                
            </fieldset>
            
            <fieldset>
                <label for="weapon-type">Choisir le type d'arme </label>
                <select name="weapon-type" id="weapon-type">
                    <option value="">--Choisir le type d'arme --</option>
                    <option value="Arc">1 - Arc</option>
                    <option value="Catalyst">2 - Catalyseur</option>
                    <option value="Espadon">3 - Epée à deux mains</option>
                    <option value="Lance">4 - Lance</option>
                    <option value="Sword">5 - Epée à une main</option>
                </select> 
            </fieldset>
            
            <fieldset>
                <label for="element-type">Choisir le type d'élément </label>
                <select name="element-type" id="element-type">
                    <option value="">Choisir le type d'élément </option>
                    <option value="1">1 - Anémo</option>
                    <option value="2">2 - Cryo</option>
                    <option value="3">3 - Electro</option>
                    <option value="6">4 - Géo</option>
                    <option value="7">5 - Hydro</option>
                    <option value="8">6 - Pyro</option>
                </select>
            </fieldset>
            
            <fieldset>
                <label for="faceUpload">Portrait</label>
              <input type="file" name="faceUpload" id="faceUpload">
            </fieldset>
            
            <fieldset>
                <label for="buildUpload">Image du build </label>
                <input type="file" name="buildUpload" id="buildUpload">
            </fieldset>
            
            <fieldset>
                <textarea maxlength="500" id="description" name="description"
                          rows="5" cols="50">Description du build
                </textarea>            
            </fieldset>
            
            <input type="submit" value="Créer le personnage">
            
        </form>
              
    </body>
</html>                                
        