<?php include "../layout/metadata.php";

$ddb = new Dbconnect();


if(!empty($_POST)){
        if(
                isset($_POST['charname'],$_POST['weapon-type'],$_POST['element-type'],$_FILES['faceUpload']['full_path'], $_FILES['buildUpload']['full_path'])
        ){
                $charname = strip_tags($_POST['charname']);
                $description = htmlspecialchars($_POST['description']);
                
        }if($_POST['weapon-type']=='arc'){
                $weaponicon = "../../ressources/arc.png";
        }if($_POST['weapon-type']=='catalyst'){
                $weaponicon = "../../ressources/catalyst.png";
        }if($_POST['weapon-type']=='espadon'){
                $weaponicon = "../../ressources/espadon.png";
        }if($_POST['weapon-type']=='lance'){
                $weaponicon = "../../ressources/lance.png";
        }if($_POST['weapon-type']=='sword'){
                $weaponicon = "../../ressources/sword.png";
        }
        
        $sql1 = "INSERT INTO characters (name, portrait_url, category_id, weapon_name, weapon_icon) VALUE (:charname, :faceUpload, :element_type, :weapon_type, :weapon_icon)";
        
        $query = $ddb->db->prepare($sql1);
        $query->bindValue(':charname', $charname);
        $query->bindValue(':faceUpload',$_FILES['faceUpload']['full_path']);
        $query->bindValue(':element_type',intval($_POST['element-type']));
        $query->bindValue(':weapon_type', $_POST['weapon-type']);
        $query->bindValue(':weapon_icon',$weaponicon);
        var_dump($_POST['weapon-type']);
        var_dump($_POST['element-type']);
        var_dump(intval($_POST['element-type']));
        var_dump($_FILES['faceUpload']['full_path']);
        var_dump($charname);
        var_dump($weaponicon);
        $query->execute();
        
        $id = $ddb->db->lastInsertId();

        
        $sql3 = "INSERT INTO builds (description, image_URL) VALUE (:description, :image_url) WHERE character_id = :character_id";
        $query = $ddb->db->prepare($sql3);
        $query->bindValue(':character_id',intval($id) );
        $query->bindValue(':description', $description);
        $query->bindValue(':image_url', $_FILES['buildUpload']['full_path']);
        var_dump($id);
        var_dump(intval($id));
        
        var_dump($description);
        var_dump($_FILES['buildUpload']['full_path']);
        $query->execute();
        
}








?>