<table>

    <thead>
        <tr class="hover_white">
            <th>Pseudonyme</th>
            <th>Email</th>
            <th>Role (1 = admin / 0 = non-admin)</th>
            <th>Suppression</th>
        </tr>
    </thead>
    <tbody>
<?php
require "../src/managers/UserManager.php";
$userManager = new UserManager();
$userArray= $userManager->getUsers();

// require "../src/controller/AdminPanelController.php";
// $manageUser = new AdminPanelController();
// $deleteuser = $manageuser->manageUser();

var_dump($userArray);
var_dump($_POST);
for($i=0,$max=count($userArray);$i<$max;$i++){
?>
        <tr>
            <td><?=$userArray[$i]['name']?></td>
            <td><?=$userArray[$i]['email']?></td>
            <td><?=$userArray[$i]['is_admin']?></td>
            <td>
                <form action="" method="post">
                <input type="hidden" name="userId" value=<?=$userArray[$i]['ID']?>>
                <button type="submit" class="deletebtn">Supprimer l'utilisateur</button>
                </form>
            </td>
        </tr>

<?php

}
?>
    </tbody>
</table>