<!doctype html>
<html lang="fr">
<?php
require "../src/managers/Buildmanager.php";
$buildManager = new BuildManager();
$build=$buildManager->getAllBuilds();





var_dump($_POST);
?>
<head>
                
</head>
        <body>
                <form class="admin-form" action="index.php?route=adminUpdate" method="post" enctype="multipart/form-data">
                        <fieldset>
                                <select name="build" id="build">
                                                
                                                
<?php                                                
for($i=0,$max=count($build);$i<$max;$i++){
$characterId = $build[$i]['ID'];
$charactername = $build[$i]['image_URL'];
?>       
                                                
                                               
                                        <option value = <?=$characterId?>>
                                        <?=$charactername?> </option>
<?php
}
?> 
                                        </select>
                                </fieldset>

                                <fieldset>
                                        <label for="updateBuild">Nouvelle image </label>
                                        
                                        <input type="file" name="updateBuild"/>
                                        <input type="submit" value="Remplacer le build"/> 
                                </fieldset>
                        </form>
                </body>
</html>

<?php

// if(isset($_POST)){
//         $editbuild = $buildManager->editBuildByBuildId($_POST['image_URL']);
// }


?>