<table>

    <thead>
        <tr class="hover_white">
            <th>Pseudonyme</th>
            <th>Email</th>
            <th>Role (1 = admin / 0 = non-admin)</th>
            <th>Suppression</th>
        </tr>
    </thead>
    <tbody>
<?php

require "../src/managers/UserManager.php";
$userManager = new UserManager();


if(isset($_POST["userId"])){
    $userManager->deleteUserById($_POST['userId']);
}
    
$userArray= $userManager->getUsers();


for($i=0,$max=count($userArray);$i<$max;$i++){
?>
        <tr>
            <td><?=htmlspecialchars($userArray[$i]['name'])?></td>
            <td><?=htmlspecialchars($userArray[$i]['email'])?></td>
            <td><?=htmlspecialchars($userArray[$i]['is_admin'])?></td>
            <td>
                <form action="" method="post">
                <input type="hidden" name="userId" value=<?=$userArray[$i]['ID']?>>
                <button type="submit" class="deletebtn">Supprimer l'utilisateur</button>
                </form>
            </td>
        </tr>

<?php

}
?>
    </tbody>
</table>