<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
<?php require "../src/managers/CharacterManagers.php";
$cm = new CharacterManagers();
$characters = $cm->getCharactersByCategoryId(1);

?>
    <body>
   
        
   <div class="options-wrapper">
   <div class="options">
      <?php
      
      for($i=0, $max=count($characters); $i < $max; $i++){
         ?>
         
         <a href="?route=build&characterId=<?=$characters[$i]['ID']?>"class="option active champion-geo<?=$i+1?>">
            <img class="option active face" src="./uploads/<?=htmlspecialchars($characters[$i]['portrait_url'])?>" alt="">
         <div class="" >
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src="<?=htmlspecialchars($characters[$i]['weapon_icon'])?>" alt="">
               </div>
               <div class="info">
                  <div class="main">
                     <p><?=htmlspecialchars($characters[$i]['name'])?></p>
                  </div>
                     <p class="sub"><?=htmlspecialchars($characters[$i]['weapon_name'])?></p>
               </div>
               
            </div>
         </div>
      </a>
      <?php
      }
      ?>
</div>
</div>
</body>
</html>