<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
   <?php include "../layout/header.php" ?>
   <?php include "../layout/navigation.php" ?>
        
   <div class="options-wrapper">
   <div class="options">
      <a href="#"class="option active champion-anemo1">
         <div class="" >
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src="../../ressources/sword.png">
               </div>
               <div class="info">
                  <div class="main">Jean</div>
                  <div class="sub">Epée à une main</div>
               </div>
            </div>
         </div>
      </a>   
      <div class="option active champion-anemo2" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Kaedehara_Kazuha</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
      <div class="option active champion-anemo3" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/espadon.png">
         </div>
         <div class="info">
            <div class="main">Sayu</div>
            <div class="sub">Epée a deux mains</div>
         </div>
      </div>
   </div>
      <div class="option active champion-anemo4" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/catalyst.png">
         </div>
         <div class="info">
            <div class="main">Shikanoin Heizou</div>
            <div class="sub">Catalyseur</div>
         </div>
      </div>
   </div>
      <div class="option active champion-anemo5" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/catalyst.png">
         </div>
         <div class="info">
            <div class="main">Sucrose</div>
            <div class="sub">Catalyseur'</div>
         </div>
      </div>
   </div>
      <div class="option active champion-anemo6" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Voyageur</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
      <div class="option active champion-anemo7" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/catalyst.png">
         </div>
         <div class="info">
            <div class="main">Venti</div>
            <div class="sub">Catalyseur</div>
         </div>
      </div>
   </div>
   <div class="option active champion-anemo8" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/lance.png">
         </div>
         <div class="info">
            <div class="main">Xiao</div>
            <div class="sub">Arme d'hast</div>
         </div>
      </div>
   </div>
</div>
</div>
</body>
<?php include "../layout/script.php" ?>
</html>