<?php   include "../layout/metadata.php";
        // include "../layout/header.php";
        // include "../page/form.php";
       
        
        
        // a enelever une fosi le routing fait
        // require "../classes/db_connect.php";
        $ddb = new Dbconnect();
        
                            

        //on traite le formulaire
        if(!empty($_POST)){
            // var_dump($_POST);
            //POST n'est pas vide , on verifie que tte les données sont présentes
            if(
                isset($_POST["name"], $_POST["email"], $_POST["password"]) && !empty($_POST["name"]) && !empty($_POST["email"]) && !empty($_POST["password"])
            ){
                //formulaire complet , on récupére les données en les protégeant (XSS)
                //on retire les balise de name + email + neutralisation des balise dans le password
                $name = strip_tags($_POST["name"]);
                $email = strip_tags($_POST["email"]);
                $password = htmlspecialchars($_POST["password"]);
                // on verif si l'email a le bon format
                if(!filter_var($_POST["email"], FILTER_VALIDATE_EMAIL)){
                    die("l'adresse email n'a pas le bon format ");
                }
                
                // hash du MDP
                
                $password = password_hash($_POST["password"],PASSWORD_BCRYPT);
                
                // var_dump($password);
                // on enregistre les donnée en bdd
                // require "../classes/db_connect.php";
                
                $sql = "INSERT INTO users (name, email, password, is_admin) VALUES (:pseudo, :email, :password, false)";
                
                $query = $ddb->db->prepare($sql);
                $query->bindValue(":pseudo", $name);
                $query->bindValue(":email", $_POST["email"]);
                $query->bindValue(":password", $password);
                
                $query->execute();
                
                // on conecte directement l'utilisateur
                
            }else if
                // formulaire bien envoyer , on verifie que tout les champs requis soit remplis
                (isset($_POST["emailconnexion"], $_POST["passwordconnexion"])
                && !empty($_POST["emailconnexion"] && !empty($_POST["passwordconnexion"]))
                ){
                    
                        //on verifie que l'email a le bon format
                        if(!filter_var($_POST["emailconnexion"], FILTER_VALIDATE_EMAIL)){
                                die("l'adresse email n'a pas le bon format");
                        }else
                        {
                            
                            $sql ="SELECT * FROM users WHERE email = :email";
                        
                        $query = $ddb->db->prepare($sql);
                        $query->bindValue(":email", $_POST["emailconnexion"]);
                        $query->execute();
                        
                        $user = $query->fetch();
                        
                        
                        if(!$user){
                            die("L'utilisateur et/ou le mot de passe est incorrect 2 ");
                        }
                        // confirmation de l'existance du user, on peut verif sont MDP
                        if(!password_verify($_POST["passwordconnexion"], $user["password"])){
                            die("L'utilisateur et/ou le mot de passe est incorrect");
                        }
                        //si l'utilisateur et le mdp sont corrects on va pouvoir connecté l'utilisateur
                        //on démarre la session PHP via session_start
                        // session_start();
                        
                        
                        //on stock dans $_SESSIONS les info de l'utilisateur
                        $_SESSION["user"] = [
                            "id" => $user["ID"],
                            "pseudo" => $user["name"],
                            "email" => $user["email"],
                            "is_admin" => $user["is_admin"]
                        ];
                        
                        
                        // on redirige vers la page d'acueille
                        
                        
                        
                            
                        
                            
                        }
                }
        }
        else{
                die("Le formulaire est incomplet");
            }

?>



        
        
        
        
        
