<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php"; 
require "../src/managers/Buildmanager.php";?>

    <body>
   <div class="build_disclaimer">
           <p>Ceci n'est qu'une proposition de build, d'autres variantes existes </p>
   </div>
   
       <div class="build_layout">
               
         <?php


         $characterId = $_GET['characterId'];
         $bm = new Buildmanager();
         $build = $bm->getBuildByCharacterId($characterId);
         
        
        $buildUrl="./uploads/".$build;
        
        
         ?>      
        <img class="build_layout" src=<?=$buildUrl?> alt="">
<?php
        if(isset($_SESSION['user']))
        {
        include "write_message.phtml";
        }else{
            
        }
        
?>
        
        
        
       </div> 
  
</body>
</html>

