<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
   <?php include "../layout/header.php" ?>
   <?php include "../layout/navigation.php" ?>
   <div class="build_disclaimer">
           <p>Ceci n'est qu'une proposition de build, d'autres variantes existes </p>
   </div>
   
       <div class="build_layout"></div> 
  
</body>
<?php include "../layout/script.php" ?>
</html>