<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
   <div class="build_disclaimer">
           <p>Ceci n'est qu'une proposition de build, d'autres variantes existes </p>
   </div>
   
       <div class="build_layout">
               
         <?php
         include "../src/managers/Buildmanager.php"
         ?>      
               
       </div> 
  
</body>
</html>

