<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
   
        
   <div class="options-wrapper">
   <div class="options">
      <a href="#"class="option active champion-cryo1">
         <div class="" >
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src="../../ressources/arc.png">
               </div>
               <div class="info">
                  <div class="main">Alloy</div>
                  <div class="sub">Archére</div>
               </div>
            </div>
         </div>
      </a>   
      <div class="option active champion-cryo2" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/espadon.png">
         </div>
         <div class="info">
            <div class="main">Chongyun</div>
            <div class="sub">Epée a deux mains</div>
         </div>
      </div>
   </div>
      <div class="option active champion-cryo3" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/arc.png">
         </div>
         <div class="info">
            <div class="main">Diona</div>
            <div class="sub">Archére</div>
         </div>
      </div>
   </div>
      <div class="option active champion-cryo4" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/espadon.png">
         </div>
         <div class="info">
            <div class="main">Eula</div>
            <div class="sub">Epée à deux mains</div>
         </div>
      </div>
   </div>
      <div class="option active champion-cryo5" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/arc.png">
         </div>
         <div class="info">
            <div class="main">Ganyu</div>
            <div class="sub">Archére</div>
         </div>
      </div>
   </div>
      <div class="option active champion-cryo6" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Kaeya</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
      <div class="option active champion-cryo7" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Kamisato Ayaka</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
   <div class="option active champion-cryo8" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Qiqi</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
   <div class="option active champion-cryo9" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/lance.png">
         </div>
         <div class="info">
            <div class="main">Rosaria</div>
            <div class="sub">Arme d'hast</div>
         </div>
      </div>
   </div>
   <div class="option active champion-cryo10" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/lance.png">
         </div>
         <div class="info">
            <div class="main">Shenhe</div>
            <div class="sub">Arme d'hast</div>
         </div>
      </div>
   </div>
</div>
</div>
</body>
<?php include "../layout/script.php" ?>
</html>
