<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
   
        
   <div class="options-wrapper">
   <div class="options">
      <a href="#"class="option active champion-electro1">
         <div class="" >
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src="../../ressources/espadon.png">
               </div>
               <div class="info">
                  <div class="main">Beidou</div>
                  <div class="sub">Epée a deux main</div>
               </div>
            </div>
         </div>
      </a>   
      <div class="option active champion-electro2" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/arc.png">
         </div>
         <div class="info">
            <div class="main">Fischl</div>
            <div class="sub">Archére</div>
         </div>
      </div>
   </div>
      <div class="option active champion-electro3" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Keqing</div>
            <div class="sub">Epée a une main</div>
         </div>
      </div>
   </div>
      <div class="option active champion-electro4" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/arc.png">
         </div>
         <div class="info">
            <div class="main">Kujou Sara</div>
            <div class="sub">Archére</div>
         </div>
      </div>
   </div>
      <div class="option active champion-electro5" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Kuki Shinob</div>
            <div class="sub">Epée a une main</div>
         </div>
      </div>
   </div>
      <div class="option active champion-electro6" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/catalyst.png">
         </div>
         <div class="info">
            <div class="main">Lisa</div>
            <div class="sub">Catalyseur</div>
         </div>
      </div>
   </div>
      <div class="option active champion-electro7" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/lance.png">
         </div>
         <div class="info">
            <div class="main">Raiden Shogun</div>
            <div class="sub">Arme d'hast</div>
         </div>
      </div>
   </div>
   <div class="option active champion-electro8" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/espadon.png">
         </div>
         <div class="info">
            <div class="main">Razor</div>
            <div class="sub">Epée à deux mains</div>
         </div>
      </div>
   </div>
   <div class="option active champion-electro9" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Voyageur</div>
            <div class="sub">Epée a une main</div>
         </div>
      </div>
   </div>
   <div class="option active champion-electro10" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/catalyst.png">
         </div>
         <div class="info">
            <div class="main">Yae Miko</div>
            <div class="sub">Catalyseur</div>
         </div>
      </div>
   </div>
</div>
</div>
</body>
</html>
