<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
<?php require "../src/managers/CharacterManagers.php";
$cm = new CharacterManagers();
$characters = $cm->getCharactersByCategoryId(6);

?>
    <body>
        
   <div class="options-wrapper">
      <div class="options">
      
      <?php
      
      for($i=0, $max=count($characters); $i < $max; $i++){
         ?>
         
         <a href="?route=build&characterId=<?=$characters[$i]['ID']?>"class="option active champion-geo<?=$i+1?>">

         <div class="option active" >
                        <img class=" face" src="./uploads/<?=$characters[$i]['portrait_url']?>" alt="">
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src=<?=$characters[$i]['weapon_icon']?>>
               </div>
               <div class="info">
                  
                     <p class="main"><?=$characters[$i]['name']?></p>
                  
                     <p class="sub"><?=$characters[$i]['weapon_name']?></p>
               </div>
               
            </div>
         </div>
      </a>
      <?php
      }
     
      ?>
      
      </div>
   </div>
</body>
</html>
