<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
        
   <div class="options-wrapper">
   <div class="options">
      <a href="?route=build&characterId=1"class="option active champion-geo1">
         <div class="" >
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src="../../ressources/espadon.png">
               </div>
               <div class="info">
                  <div class="main">Itto</div>
                  <div class="sub">Epée à deux mains</div>
               </div>
            </div>
         </div>
      </a>   
      <div class="option active champion-geo2" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/catalyst.png">
         </div>
         <div class="info">
            <div class="main">Ningguang</div>
            <div class="sub">Catalyseur</div>
         </div>
      </div>
   </div>
      <div class="option active champion-geo3" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/arc.png">
         </div>
         <div class="info">
            <div class="main">Gorou</div>
            <div class="sub">Archer</div>
         </div>
      </div>
   </div>
      <div class="option active champion-geo4" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/espadon.png">
         </div>
         <div class="info">
            <div class="main">Noelle</div>
            <div class="sub">Epée à deux mains</div>
         </div>
      </div>
   </div>
      <div class="option active champion-geo5" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/lance.png">
         </div>
         <div class="info">
            <div class="main">Zhongli</div>
            <div class="sub">Arme d'hast</div>
         </div>
      </div>
   </div>
      <div class="option active champion-geo6" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Albedo</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
      <div class="option active champion-geo7" >
      <div class="shadow"></div>
      <div class="label">
         <div class="icon">
            <img class="icon" src="../../ressources/sword.png">
         </div>
         <div class="info">
            <div class="main">Voyageurs</div>
            <div class="sub">Epée à une main</div>
         </div>
      </div>
   </div>
</div>
</div>
</body>
</html>
