<div class= sociaux-timeline>
            
            <div><a class="twitter-timeline" data-lang="fr" data-width="400" data-height="550" href="https://twitter.com/genshinimpactfr?ref_src=twsrc%5Etfw">Tweets by genshinimpactfr</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>
            <a class="interactive-map" href="https://www.genshin-impact.fr/map/"target="blanck"><div class="interactive-map"><div class="map-sign">Map interactive</div></div></a>
            <a class ="insta-timeline" href="https://www.instagram.com/teyvat.fr/"><div class="insta-feed" data-mc-src="75329645-13b5-4b8c-851a-96e1d3fa8e47#instagram"></div></a>
            <a class="gensh-event"href="https://genshin.hoyoverse.com/fr/news" target="_blank"><div class="event-sign">Les news</div></a>
        
        
        <script 
  src="https://cdn2.woxo.tech/a.js#62eb7af40475c458d67056dc" 
  async data-usrc>
</script>