<!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
<?php require "../src/managers/CharacterManagers.php";
$cm = new CharacterManagers();
$characters = $cm->getCharactersByCategoryId(8);

?>
    <body>
   
        
   <div class="options-wrapper">
   <div class="options">
      <?php
      
      for($i=0, $max=count($characters); $i < $max; $i++){
         ?>
         
         <a href="?route=build&characterId=<?=$characters[$i]['ID']?>"class="option active champion-geo<?=$i+1?>">
            <img class="option active face" src="./uploads/<?=htmlspecialchars($characters[$i]['portrait_url'])?>" alt="">
         <div class="" >
            <div class="shadow"></div>
            <div class="label">
               <div class="icon">
                  <img class="icon" src="<?=htmlspecialchars($characters[$i]['weapon_icon'])?>" alt="">
               </div>
               <div class="info">
                  <div class="main">
                     <p><?=htmlspecialchars($characters[$i]['name'])?></p>
                  </div>
                     <p class="sub"><?=htmlspecialchars($characters[$i]['weapon_name'])?></p>
               </div>
               
            </div>
         </div>
      </a>
      <?php
      }
      ?>
</div>
</div>
</body>
</html>



<!--<!DOCTYPE html>-->
<!--<html lang="fr">-->
<!--<?php include "../layout/metadata.php" ?>-->
<!--    <body>-->
   
        
<!--   <div class="options-wrapper">-->
<!--   <div class="options">-->
<!--      <a href="#"class="option active champion-pyro1">-->
<!--         <div class="" >-->
<!--            <div class="shadow"></div>-->
<!--            <div class="label">-->
<!--               <div class="icon">-->
<!--                  <img class="icon" src="../../ressources/arc.png">-->
<!--               </div>-->
<!--               <div class="info">-->
<!--                  <div class="main">Amber</div>-->
<!--                  <div class="sub">Archére</div>-->
<!--               </div>-->
<!--            </div>-->
<!--         </div>-->
<!--      </a>   -->
<!--      <div class="option active champion-pyro2" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/sword.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Bennett</div>-->
<!--            <div class="sub">Epée a une mains</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--      <div class="option active champion-pyro3" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/espadon.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Diluc</div>-->
<!--            <div class="sub">Epée a deux mains</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--      <div class="option active champion-pyro4" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/lance.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Hu Tao</div>-->
<!--            <div class="sub">Arme d'hast</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--      <div class="option active champion-pyro5" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/catalyst.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Klee</div>-->
<!--            <div class="sub">Catalyseur</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--      <div class="option active champion-pyro6" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/lance.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Thoma</div>-->
<!--            <div class="sub">Arme d'hast</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--      <div class="option active champion-pyro7" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/lance.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Xiangling</div>-->
<!--            <div class="sub">Arme d'hast</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--   <div class="option active champion-pyro8" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/espadon.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Xinyan</div>-->
<!--            <div class="sub">Arme a deux mains</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--   <div class="option active champion-pyro9" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/catalyst.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Yanfei</div>-->
<!--            <div class="sub">Catalyseur</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--   <div class="option active champion-pyro10" >-->
<!--      <div class="shadow"></div>-->
<!--      <div class="label">-->
<!--         <div class="icon">-->
<!--            <img class="icon" src="../../ressources/arc.png">-->
<!--         </div>-->
<!--         <div class="info">-->
<!--            <div class="main">Yoimiya</div>-->
<!--            <div class="sub">Archére</div>-->
<!--         </div>-->
<!--      </div>-->
<!--   </div>-->
<!--</div>-->
<!--</div>-->
<!--</body>-->
<!--</html>-->
