<?php
        //on traite le formulaire
        if(!empty($_POST)){
            var_dump($_POST);
            //POST n'est pa s vide , on verifie que tte les données sont présentes
            if(
                isset($_POST["name"], $_POST["email"], $_POST["password"]) && !empty($_POST["name"]) && !empty($_POST["email"]) && !empty($_POST["password"])
            ){
                //formulaire complet , on récupére les données en les protégeant (XSS)
                //on retire les balise de name + email + neutralisation des balise dans le password
                $name = strip_tags($_POST["name"]);
                $email = strip_tags($_POST["email"]);
                $password = htmlspecialchars($_POST["password"]);
                // on verif si l'email a le bon format
                if(!filter_var($_POST["email"], FILTER_VALIDATE_EMAIL)){
                    die("l'adresse email n'a pas le bon format  ");
                }
                
                // hash du MDP
                
                $password = password_hash($_POST["password"],PASSWORD_ARGON2ID);
                
                var_dump($password);
                // on enregistre les donnée
                
            }else{
                die("Le formulaire est incomplet");
            }
        }
        ?><!DOCTYPE html>
<html lang="fr">
<?php include "../layout/metadata.php" ?>
    <body>
        <?php include "../layout/header.php" ?>
        
        
        
        <form class="log-form" action="" method="post">
            <label class="form_name" for="text" id="text" name="form_name" >Connexion</label>
          <div>
            <label for="name">Nom&nbsp;:</label>
            <input type="text" id="name" name="name" />
          <div>
          <div>
            <label for="mail">E-mail&nbsp;:</label>
            <input type="email" id="mail" name="email" required/>
        <div>
            <label for="password">Mot de passe&nbsp;:</label>
            <input type="password" name="password" required/>
        </div>
          </div>
          
          <button type="submit" onclick="sendData({test:'ok'})">let's go!</button>
        </form>
        
    </body>
</html>