<?php
require "../src/controller/ComentsController.php"
?>

<h2 class="comments-title">Espace commentaires</h2>
        <form class="comments" method="POST" action=<?= 'index.php?route=build&characterId='.$characterId ?>>
                <input type="hidden" name="userId" value <?= $_SESSION['user']['id']?>> </input>
                <input type="hidden" name="buildId" value=<?= $characterId?>> </input>  
            <fieldset>
                <textarea id="comments_box" name="comments"
                          rows="5" cols="94" placeholder="Ecrivez votre commentaire">
                </textarea>
        
                <button class="submit">Envoyer</button>
            </fieldset>
        </form>