<?php

?>

<h2 class="comments-title">Espace commentaires</h2>
        <form class="comments" method="POST" action="<?php echo 'index.php?=build&characterId='.$characterId ?>">
                <input type="hidden" name="user_ID" value <?= $user_ID?>> </input>
                <input type="hidden" name="buildId" value=<?= $buildId?>> </input>  
            <fieldset>
                <textarea id="comments_box" name="comments"
                          rows="5" cols="94" placeholder="Ecrivez votre commentaire">
                </textarea>
        
                <button class="submit">Envoyer</button>
            </fieldset>
        </form>